### ISSUE TITLE
Error during Prediction if Keypoints are excluded - Follow up to solved Bug #73

### ISSUE THREAD

**Issue by Mijar007** [YttriLab/A-SOID#82]
**Describe the bug**
12 Keypoints are in DLC pose file. 4 where excluded during learning. No errors during learning.
After training, new pose files containing the original 12 keypoints where given for prediction.
Pushing the "Predict and Generate Summary Statistics" afterwards raised the following error:

```
IndexError: index 8 is out of bounds for axis 1 with size 8
Traceback:
File "C:\ProgramData\anaconda3\envs\asoid\lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 535, in _run_script
    exec(code, module.__dict__)
File "C:\Users\Rabenstein\Python\A-SOID-main\asoid\app.py", line 328, in <module>
    main()
File "C:\Users\Rabenstein\Python\A-SOID-main\asoid\app.py", line 317, in main
    F_predict.main(ri=ri, config=st.session_state['config'])
File "C:\Users\Rabenstein\Python\A-SOID-main\asoid\apps\F_predict.py", line 773, in main
    predict_annotate_video(ftype, software, is_3d, multi_animal, selected_bodyparts, llh_value,
File "C:\Users\Rabenstein\Python\A-SOID-main\asoid\apps\F_predict.py", line 460, in predict_annotate_video
    filt_pose, _ = adp_filt(current_pose, idx_selected, idx_llh, llh_value)
File "C:\Users\Rabenstein\Python\A-SOID-main\asoid\utils\preprocessing.py", line 65, in adp_filt
    currdf_filt[0, (2 * x):(2 * x + 2)] = np.hstack([datax[0, x], datay[0, x]])
```

**Expected behavior**
The tool should only use the keypoints used during training and ignore the rest.

**Screenshots**
![image](https://github.com/YttriLab/A-SOID/assets/67411312/164be0c2-b535-4128-94df-5da6ea8d7c89)

**Project Config (please post the content of the corresponding config.ini file)**

[Project]
PROJECT_TYPE = DeepLabCut
PROJECT_NAME = Apr-11-2024_test2
PROJECT_PATH = C:\Users\Rabenstein/Desktop/asoid_output
FRAMERATE = 24
KEYPOINTS_CHOSEN = Nose, Front_Right_1, Front_Left_1, Rear_Right_1, Rear_Left_1, Midline_Front, Midline_Center, Midline_Rear
EXCLUDE_OTHER = False
FILE_TYPE = csv
INDIVIDUALS_CHOSEN = single animal
CLASSES = Wiggle, other
MULTI_ANIMAL = False
IS_3D = False

[Data]
DATA_INPUT_FILES = GOPR0622DLC_resnet50_Wiggle_TestJan26shuffle1_100000.csv, GOPR0623DLC_resnet50_Wiggle_TestJan26shuffle1_100000.csv, GOPR0624DLC_resnet50_Wiggle_TestJan26shuffle1_100000.csv, GOPR0625DLC_resnet50_Wiggle_TestJan26shuffle1_100000.csv, GOPR0626DLC_resnet50_Wiggle_TestJan26shuffle1_100000.csv, GOPR0627DLC_resnet50_Wiggle_TestJan26shuffle1_100000.csv, GOPR0628DLC_resnet50_Wiggle_TestJan26shuffle1_100000.csv, GOPR0629DLC_resnet50_Wiggle_TestJan26shuffle1_100000.csv, GOPR0630DLC_resnet50_Wiggle_TestJan26shuffle1_100000.csv, GOPR0631DLC_resnet50_Wiggle_TestJan26shuffle1_100000.csv, GOPR0632DLC_resnet50_Wiggle_TestJan26shuffle1_100000.csv, GOPR0633DLC_resnet50_Wiggle_TestJan26shuffle1_100000.csv, GOPR0634DLC_resnet50_Wiggle_TestJan26shuffle1_100000.csv, GOPR0635DLC_resnet50_Wiggle_TestJan26shuffle1_100000.csv, GOPR0636DLC_resnet50_Wiggle_TestJan26shuffle1_100000.csv, GOPR0637DLC_resnet50_Wiggle_TestJan26shuffle1_100000.csv, GOPR0638DLC_resnet50_Wiggle_TestJan26shuffle1_100000.csv, GOPR0639DLC_resnet50_Wiggle_TestJan26shuffle1_100000.csv, GOPR0640DLC_resnet50_Wiggle_TestJan26shuffle1_100000.csv, GOPR0641DLC_resnet50_Wiggle_TestJan26shuffle1_100000.csv, GOPR0642DLC_resnet50_Wiggle_TestJan26shuffle1_100000.csv, GOPR0643DLC_resnet50_Wiggle_TestJan26shuffle1_100000.csv, GOPR0644DLC_resnet50_Wiggle_TestJan26shuffle1_100000.csv, GOPR0645DLC_resnet50_Wiggle_TestJan26shuffle1_100000.csv, GOPR0646DLC_resnet50_Wiggle_TestJan26shuffle1_100000.csv, GOPR0647DLC_resnet50_Wiggle_TestJan26shuffle1_100000.csv, GOPR0648DLC_resnet50_Wiggle_TestJan26shuffle1_100000.csv, GOPR0649DLC_resnet50_Wiggle_TestJan26shuffle1_100000.csv, GOPR0650DLC_resnet50_Wiggle_TestJan26shuffle1_100000.csv, GOPR0651DLC_resnet50_Wiggle_TestJan26shuffle1_100000.csv, GOPR0652DLC_resnet50_Wiggle_TestJan26shuffle1_100000.csv, GOPR0653DLC_resnet50_Wiggle_TestJan26shuffle1_100000.csv, GOPR0654DLC_resnet50_Wiggle_TestJan26shuffle1_100000.csv, GOPR0655DLC_resnet50_Wiggle_TestJan26shuffle1_100000.csv, GOPR0656DLC_resnet50_Wiggle_TestJan26shuffle1_100000.csv, GOPR0657DLC_resnet50_Wiggle_TestJan26shuffle1_100000.csv, GOPR0658DLC_resnet50_Wiggle_TestJan26shuffle1_100000.csv, GOPR0659DLC_resnet50_Wiggle_TestJan26shuffle1_100000.csv, GOPR0660DLC_resnet50_Wiggle_TestJan26shuffle1_100000.csv, GOPR0661DLC_resnet50_Wiggle_TestJan26shuffle1_100000.csv
LABEL_INPUT_FILES = GOPR0622.avi_No focal subject.tsv, GOPR0623.avi_No focal subject.tsv, GOPR0624.avi_No focal subject.tsv, GOPR0625.avi_No focal subject.tsv, GOPR0626.avi_No focal subject.tsv, GOPR0627.avi_No focal subject.tsv, GOPR0628.avi_No focal subject.tsv, GOPR0629.avi_No focal subject.tsv, GOPR0630.avi_No focal subject.tsv, GOPR0631.avi_No focal subject.tsv, GOPR0632.avi_No focal subject.tsv, GOPR0633.avi_No focal subject.tsv, GOPR0634.avi_No focal subject.tsv, GOPR0635.avi_No focal subject.tsv, GOPR0636.avi_No focal subject.tsv, GOPR0637.avi_No focal subject.tsv, GOPR0638.avi_No focal subject.tsv, GOPR0639.avi_No focal subject.tsv, GOPR0640.avi_No focal subject.tsv, GOPR0641.avi_No focal subject.tsv, GOPR0642.avi_No focal subject.tsv, GOPR0643.avi_No focal subject.tsv, GOPR0644.avi_No focal subject.tsv, GOPR0645.avi_No focal subject.tsv, GOPR0646.avi_No focal subject.tsv, GOPR0647.avi_No focal subject.tsv, GOPR0648.avi_No focal subject.tsv, GOPR0649.avi_No focal subject.tsv, GOPR0650.avi_No focal subject.tsv, GOPR0651.avi_No focal subject.tsv, GOPR0652.avi_No focal subject.tsv, GOPR0653.avi_No focal subject.tsv, GOPR0654.avi_No focal subject.tsv, GOPR0655.avi_No focal subject.tsv, GOPR0656.avi_No focal subject.tsv, GOPR0657.avi_No focal subject.tsv, GOPR0658.avi_No focal subject.tsv, GOPR0659.avi_No focal subject.tsv, GOPR0660.avi_No focal subject.tsv, GOPR0661.avi_No focal subject.tsv
ROOT_PATH = None

[Processing]
LLH_VALUE = 0.1
ITERATION = 0
MIN_DURATION = 0.1
TRAIN_FRACTION = 0.1
MAX_ITER = 100
MAX_SAMPLES_ITER = 40
CONF_THRESHOLD = 0.75
N_SHUFFLED_SPLIT = None

**Additional context**

**Comment by JensBlack** [comment]
Hi @Mijar007,

just came back from a vacation. Thanks for your patience. I will work on this ASAP and let you know if I have any further questions.

**Comment by JensBlack** [comment]
@Mijar007 Thank you for your patience. It took longer than expected, but the issue is fixed now!

**Comment by danielpollak** [comment]
I still have this issue. I was able to get it to work by including all keypoints. Here is the metadata:

[Project]
PROJECT_TYPE = DeepLabCut
PROJECT_NAME = physiology_Dec-15-2025
PROJECT_PATH = C:\Users\dan/Desktop/asoid_output
FRAMERATE = 30
KEYPOINTS_CHOSEN = snout, neck, spine1, spinecenter, spine3, tailbase, leftear, rightear, puck, food, hand
EXCLUDE_OTHER = False
FILE_TYPE = csv
INDIVIDUALS_CHOSEN = single animal
CLASSES = approach, dart, rear, other
MULTI_ANIMAL = False
IS_3D = False

[Data]
DATA_INPUT_FILES = stitched-videoDLC_Resnet50_mousehuntFeb25shuffle1_snapshot_200.csv
LABEL_INPUT_FILES = stitched-videoDLC_Resnet50_mousehuntFeb25shuffle1_snapshot_200_p60_labeled.mp4_No focal subject.tsv
ROOT_PATH = None

[Processing]
LLH_VALUE = 0.1
ITERATION = 0
MIN_DURATION = 0.18000000000000005
TRAIN_FRACTION = 0.14
MAX_ITER = 100
MAX_SAMPLES_ITER = 40
CONF_THRESHOLD = 0.5
N_SHUFFLED_SPLIT = None

It appears to me to be that there is no forwarding of included keypoints in the refinement step. Line 441 in manual_refinement.py is what crashes, and looks like this:

`adp_filt(current_pose, idx_selected, idx_llh, llh_value)`

current pose comes from 

`current_pose = load_pose(f, origin=software.lower(), multi_animal=multi_animal)`

and as far as I can tell, load_pose loads the whole dataframe (I am using DLC as my pose estimator). Not sure if this is new info but hope it helps.
